### This is a comment
POST http://localhost:3000/auth/register
Content-Type: application/json

{ "username": "newnewuser", "password": "otherpassword" }

### This is a comment
POST http://localhost:3000/auth/login
Content-Type: application/json

{ "username": "newnewuser", "password": "otherpassword" }

